ekf_filter_node:
  frequency: 50.0
  sensor_timeout: 0.1
  two_d_mode: true
  publish_tf: true
  map_frame: map
  odom_frame: odom
  base_link_frame: base_footprint
  world_frame: map  # Publish map → odom

  # Input topics
  odom0: /odom      # Gazebo’s odometry
  imu0: /imu   # IMU data

  # Odom0 Configuration (use velocities only)
  odom0_config: [false, false, false,   # Disable X/Y/Z position
                 false, false, false,   # Disable orientation
                 true,  true,  false,  # Use X/Y linear velocity
                 false, false, true]   # Use Z angular velocity (yaw rate)

  # IMU Configuration (use orientation and angular velocity)
  imu0_config: [false, false, false,   # Disable position
                true,  true,  true,    # Enable orientation (roll, pitch, yaw)
                false, false, false,   # Disable velocity
                true,  true,  true,    # Enable angular velocity
                true,  true,  true]    # Enable linear acceleration
