leftweb_position_controller:
  type: effort_controllers/JointPositionController
  joint: leftweb
  pid: {p: 100.0, i: 0.01, d: 10.0}

leftwheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: leftwheel
  pid: {p: 100.0, i: 0.01, d: 10.0}
  
rightweb_position_controller:
  type: effort_controllers/JointPositionController
  joint: rightweb
  pid: {p: 100.0, i: 0.01, d: 10.0}
  
rightwheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: rightwheel
  pid: {p: 100.0, i: 0.01, d: 10.0}
  
castorjoint_position_controller:
  type: effort_controllers/JointPositionController
  joint: castorjoint
  pid: {p: 100.0, i: 0.01, d: 10.0}
  
castorwheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: castorwheel
  pid: {p: 100.0, i: 0.01, d: 10.0}
